### PR TITLE
Single date range

### PR DESCRIPTION
**Pull request by ckald**
I implemented a support for 1-day-long date ranges, as discussed, e.g. in https://github.com/onefinestay/react-daterange-picker/issues/18

### CODE REVIEW

**Comment by AndrewIngram** [comment]
Thanks! Just couple of points:

1. There's no need to increment the version, we do this ourselves as part of the release process.
2. This functionally really needs to be made optional behind a boolean prop, because for our use cases we don't want to allow this functionality. In future we'll look into a more robust mechanism for defining the validating of a selection.

**Comment by ckald** [comment]
Done. Meet `singleDateRange` prop (disabled by default) and an example of how it works.

**Comment by stingrayfunk** [comment]
Thanks so much for this! :-)

**Comment by jkimbo** [comment]
This is great thanks @ckald ! Just so you know we are thinking of potentially adding in an api so people can add in their own custom validation in the future but for the moment I'll get this out.

**Comment by jkimbo** [comment]
Published as `v0.8.0`

**Comment by ckald** [comment]
No problem, thanks for merging

**Pull request merged**
