### PR TITLE
Update dependencies and fix tests for React 15

### PR DESCRIPTION
**Pull request by thathenderson**
This updates peerDependencies after the changes in a50d53c55d7b39e2add269aff7f36a591b51fa73, fixes a few nits in the example code, fixes a reference to renderToString() in the gulpfile, and updates the following things in a handful of tests:
 - fixes references to unmountComponentAtNode()
 - replaced all usage of getDOMNode() with ReactDOM.findDOMNode()
 - fixes a DOM render warning about rendering td inside tbody

After these updates, there were no console warnings in develop mode, and all tests pass:
screen shot 2016-04-21 at 12 03 05 pm

Let me know if the peerDependency semver range needs to change: I did 15.x.x because that seemed to emulate the expected range. Previously, since we were using ^0.14.0, and (I think) React was pushing minor and patches on the last digit, we would have gotten both. However, I'm up for whatever you guys think is best!

### CODE REVIEW

**Comment by thathenderson** [comment]
Any chance we could get this merged soon, @AlanFoster?

**Comment by thathenderson** [comment]
Bumping. Do you have a few minutes to take a peek @AlanFoster?

**Comment by ratson** [comment]
@AlanFoster React v15 has been released about a month and 2 patch releases were out, it should be stable enough to add support for it.

**Comment by thathenderson** [comment]
One more bump. Any project owners that could get this merged? I think React 15 support is something we would all like.

**Comment by fluse** [comment]
@AlanFoster please merge branches!!!!!!!

**Comment by wmertens** [comment]
@AlanFoster I verified this PR and it works great. The only change is that npm doesn't complain any more in projects using react-daterange-picker. It is safe to merge 👍.

**Comment by AlanFoster** [comment]
@thathenderson @wmertens Thanks guys; Will try to get this in ASAP! :+1:

**Comment by AlanFoster** [comment]
@thathenderson Thanks for the great work :+1:

**Comment by skidding** [comment]
@AlanFoster any plans to bump the pkg version and publish updates to npm? Looking forward to using it with React 15. Thanks.

**Comment by AlanFoster** [comment]
Thanks for the great work @thathenderson 

This should now be available on `npm` as version v1.1.0 - let me know if there are any issues :+1:

**Comment by thathenderson** [comment]
Will do, thanks for the merge @AlanFoster 👍

**Pull request merged**
