### PR TITLE
React 0.14 compatible

### PR DESCRIPTION
**Pull request by damountie**
Applies all recommendations from http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

Note: there is a still a warning during compilation (which I couldn't immediately see the cause of), and within the Javascript console when using (which is due to the module 'CodeSnippet'). The two may have the same cause.

### CODE REVIEW

**Comment by thathenderson** [comment]
Will this be merged in soon?

**Comment by AlanFoster** [comment]
Thanks for the PR! We'll want to get the tests from #72 merged in first, to ensure we haven't broken any functionality in the upgrade.

**Comment by AlanFoster** [comment]
Let's close this PR in favour of #79 which deals with the same problem. Would you mind reviewing that PR too?

**Comment by damountie** [comment]
@AlanFoster It makes sense to merge #79, as it addresses the now-merged tests. Sure, I'd be happy to review, but I won't have the opportunity before Monday, due to annual leave.

**Comment by AlanFoster** [comment]
@damountie No problem. Thanks for the visibility :+1:

**Pull request closed without merging**
