### PR TITLE
use moment 2.10 + moment-range 2.x

### PR DESCRIPTION
**Pull request by moimikey**
# notes
- addresses #55 to update moment-range :)
- excludes build. i can add this if necessary.

### CODE REVIEW

**Comment by moimikey** [comment]
@AndrewIngram

**Comment by DylanPiercey** [comment]
Is there an ETA on this?

**Comment by moimikey** [comment]
ETA for?

**Comment by DylanPiercey** [comment]
It getting merged - sorry :)

**Comment by moimikey** [comment]
holla!

**Comment by jkimbo** [comment]
Sorry for the delay on this. Published as 0.12.0

**Comment by moimikey** [comment]
awesome. thanks guys!

**Pull request merged**
