### PR TITLE
Add react & react-dom to devDependencies

### PR DESCRIPTION
**Pull request by andywer**
Just a minor `package.json` fix. `react` and `react-dom` had not been installed before when cloning the repo and running `npm install`, so `gulp build-dist` failed at the end of `npm install`.

### CODE REVIEW

**Comment by AlanFoster** [comment]
Thanks for the PR; Small issue with Jenkins though -

```
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.15/bin/node" "/home/travis/.nvm/versions/node/v0.12.15/bin/npm" "install"
npm ERR! node v0.12.15
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package react@15.2.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-pure-render-mixin@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-dom@15.2.1 wants react@^15.2.1
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/onefinestay/react-daterange-picker/npm-debug.log
```

Mind checking that out? :+1:

**Comment by andywer** [comment]
Drats! Will have a deeper look at it tomorrow morning...

**Comment by andywer** [comment]
Build is green again 🎉 👍

**Comment by AlanFoster** [comment]
Great, thanks for the PR :+1:

**Pull request merged**
