### PR TITLE
Fix React 15 Warnings

### PR DESCRIPTION
**Pull request by josephMG**
Followed by https://github.com/onefinestay/react-daterange-picker/pull/176
And tested in [https://travis-ci.org/josephMG/react-daterange-picker](https://travis-ci.org/josephMG/react-daterange-picker)

Please merge it, or please let me know if there are any problems.
Thanks

### CODE REVIEW

**Comment by natec8** [comment]
@AlanFoster If you approve, can you get this merged in?

**Comment by fabe** [comment]
React 16 is out today, any chance we can get this reviewed and merged? Thank you! @AlanFoster

**Comment by stephen** [comment]
Hi @AlanFoster, it would be great to get this published. If this package is going unmaintained, would you consider transferring ownership to someone else who still uses it?

**Comment by AlanFoster** [comment]
Thanks!

**Pull request merged**
