### PR TITLE
New locale prop to configure i18n.

### PR DESCRIPTION
**Pull request by miracle2k**
See #44.

### CODE REVIEW

**Comment by miracle2k** [comment]
I just noticed this now (I am getting more used to npm packages).

Since this library has it's own copy of moment.js, locales need to be loaded there, like so:

     import {} from 'react-daterange-picker/node_modules/moment/locale/de';

It will not find a locale loaded via

    import {} from 'moment/locale/de'

**Comment by nicoecheza** [comment]
+1 to merge this

**Comment by rolyatmax** [comment]
+1

**Comment by AlanFoster** [comment]
Closing in preference of #119

**Pull request closed without merging**
