### PR TITLE
Updated "i18n fix" / Migrate to Babel 6

### PR DESCRIPTION
**Pull request by maullerz**
This pull request forked from @thaerlabs PR **"i18n-fix"** #119 
With additions:
- [x] upgraded tests with loop over array of locale-values
- [x] applied [feedback](https://github.com/onefinestay/react-daterange-picker/pull/119#issuecomment-227158786)  from @wmertens
- [x] completed migration to Babel 6
- [x] upgraded test loader from **isparta-loader** (deprecated) to **babel-plugin-istanbul**
- [x] a bit of eslint fixes

Deployed and working on my gh-pages - https://maullerz.github.io/react-daterange-picker/

I am using react-daterange-picker in production from forked repo now.

About squashing PR commits:
https://help.github.com/articles/about-pull-request-merges/
```
You can merge pull requests by either
retaining all the commits in a feature branch
or by squashing all commits into a single commit.
```

### CODE REVIEW

**Comment by maullerz** [comment]
bump
@AlanFoster pls check this

**Comment by maullerz** [comment]
PR description updated
@AlanFoster need your attention
Travis CI failed because of upgrading **eslint** and **gulp-eslint**.
https://github.com/adametry/gulp-eslint/issues/161
`ESLint v3.0.0 now requires Node.js 4 or higher.`

Travis here have 0.12 node version.

What should i do with this?

**Comment by andywer** [comment]
@maullerz It's not my repo, but I would suggest dropping node 0.x support. Requiring node 4+ should be fine.

How about throwing 0.12 out of the `.travis.yml` and adding `"engines": { "node": ">= 4.0" }` to package.json? The build will be green and if someone's still running 0.12, npm will show them an error :)

I hope @AlanFoster will merge it soon if the build is green.

**Comment by maullerz** [comment]
@andywer thanks for bump 👍

**Comment by andywer** [comment]
@maullerz Took the chance to try the new PR review feature 😉

**Comment by AlanFoster** [comment]
Awesome; Thanks @maullerz

**Comment by andywer** [comment]
@AlanFoster Could you please publish the updated package? :)

**Pull request merged**
